### ISSUE TITLE
OOO Lab not working

### ISSUE THREAD

**Issue by KimWirt** [zendesklabs/out_of_office_app#221]
Hello,

None of my agents are able to set themselves to unavailable. This has been an ongoing problem for about two weeks now. It is effecting ticket response times and needs to be resolved ASAP.

Thank you,
Kim

**Comment by dpawluk** [comment]
@KimWirt 

These application are provided as is by volunteers making them in their free time. Please see [the license](https://github.com/zendesklabs/out_of_office_app/blob/master/LICENSE#L31) This message must also be acknowledged before installing the app as well. 

In any case, I would suggest providing examples of what is happening in case the app developer has the time to help with your issue. Screenshots, error messages, dates/times, etc... are invaluable, especially in situations where an error is reported. 

Lastly, it may be helpful to look at the other issues currently open for the repository. I don't think [this one](https://github.com/zendesklabs/out_of_office_app/issues/218) is related but its might be worth double checking roles and permissions, making sure nothing in your Zendesk configuration has changed recently (or at least the last two weeks) since this app has not been updated for at least two months now. 

Thanks for participating in Zendesk Labs!

**Comment by KimWirt** [comment]
If there's anyone who can help us it would be great. When we change our status from available to unavailable, the status just forces back to available. The only thing that has been changed is adding a trigger and a macro, unrelated to OOO.
![screenshot from 2017-01-24 16 00 15](https://cloud.githubusercontent.com/assets/16387080/22266532/57316d14-e24e-11e6-99c0-e578730e07c8.png)

**Comment by aculligan** [comment]
@KimWirt 

I just looked into this and couldn't replicate the issue. All my agents are able to change their availability.

I'm sorry I can't offer another answer at this time :(

**Comment by Nebopolis** [comment]
@KimWirt Can you please confirm that the system user field (`Agent Out?`) is still present and enabled on your account?

**Comment by KimWirt** [comment]
Hi, thank you. Where do I find this?

Just an FYI, I have disabled and re-enabled the app, cleared my cache and restarted my computer and am still seeing an issue.

**Comment by KimWirt** [comment]
I'm just confused as to why this is a third party app and why the Zendesk product team cannot create this? This is a necessity for providing the best customer service possible.

**Comment by Nebopolis** [comment]
@KimWirt If this functionality is something that is critical for you, I'd encourage you to make a post in the [product feedback forums](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback). The user field will be located in the admin area with all other user fields. 
<img width="286" alt="screen shot 2017-02-16 at 1 39 12 pm" src="https://cloud.githubusercontent.com/assets/59228/23037823/660663ce-f44d-11e6-907b-5931d6110545.png">
<img width="669" alt="screen shot 2017-02-16 at 1 39 33 pm" src="https://cloud.githubusercontent.com/assets/59228/23037830/6b476950-f44d-11e6-9cca-66a3fc18c020.png">

If you have deactivated the field but it is still present on your account, then reinstalling the app will not restore it. You'll have to manually activate the field in order for the app to work again. 
<img width="636" alt="screen shot 2017-02-16 at 1 41 12 pm" src="https://cloud.githubusercontent.com/assets/59228/23037878/9c8e933a-f44d-11e6-94c1-bf50ce2297ad.png">
