### ISSUE TITLE
agent_ooo not applying on 'open' tickets

### ISSUE THREAD

**Issue by I-am-Kris** [zendesklabs/out_of_office_app#226]
For some reason, the agent_ooo tag is not applying to agent tickets when the agent changes their status to unavailable, but will apply to tickets in a pending or on-hold status.  This behavior has been confirmed by zendesk customer support through zendesk ticket 2798817, who sent me in this direction for additional assistance.  Please help as this makes this very useful app a bit less useful as open tickets don't bounce out to the agents main queue when a customer updates and the agent is really ooo.

**Comment by pedrosreis** [comment]
I have the same problem. I am at your disposal to provide any necessary information that you may need.
Note: Indeed this is a great Zendesk App and extremely useful - it should be part of Zendesk core application.

**Comment by I-am-Kris** [comment]
Glad I'm not the only one? 😄

**Comment by Nebopolis** [comment]
@I-am-Kris @pedrosreis Unfortunately it isn't well documented, but what the "force unassign tickets" option controls is whether the tag is applied to open tickets. The trigger that the app installed is set up to unassign the tickets if they are in open status with that tag, but by modifying that you could achieve the workflow you are looking for. Turn on the force unassign tickets option, and then update the trigger to only unassign when there are public comment updates instead of all ticket updates.

**Comment by I-am-Kris** [comment]
This didn't used to be the case?  I thought some time ago, it automatically unassigned even tickets in an open status, without using the 'force unassign tickets'...

**Comment by Nebopolis** [comment]
@I-am-Kris There was a bug a while ago that caused the checkbox for "unassign open tickets" to be ignored, perhaps that was what you were seeing? This has been the behavior for as long as the app has been around.

**Comment by I-am-Kris** [comment]
Maybe that was it.  Anyway, I am trying out your suggestion and if I find any challenges, i'll let you know.  Thank you so much for the help.
